export const FETCH_MOVIE_SEARCH_RESULTS_START =
  'FETCH_MOVIE_SEARCH_RESULTS_START';
export const FETCH_MOVIE_SEARCH_RESULTS_SUCCESS =
  'FETCH_MOVIE_SEARCH_RESULTS_SUCCESS';
export const FETCH_MOVIE_SEARCH_RESULTS_FAILED =
  'FETCH_MOVIE_SEARCH_RESULTS_FAILED';

export const FETCH_TRENDING_MOVIES_START = 'FETCH_TRENDING_MOVIES_START';
export const FETCH_TRENDING_MOVIES_SUCCESS = 'FETCH_TRENDING_MOVIES_SUCCESS';
export const FETCH_TRENDING_MOVIES_FAILED = 'FETCH_TRENDING_MOVIES_FAILED';

export const FETCH_TV_SHOW_SEARCH_RESULTS_START =
  'FETCH_TV_SHOW_SEARCH_RESULTS_START';
export const FETCH_TV_SHOW_SEARCH_RESULTS_SUCCESS =
  'FETCH_TV_SHOW_SEARCH_RESULTS_SUCCESS';
export const FETCH_TV_SHOW_SEARCH_RESULTS_FAILED =
  'FETCH_TV_SHOW_SEARCH_RESULTS_FAILED';

export const FETCH_TRENDING_TV_SHOWS_START = 'FETCH_TRENDING_TV_SHOWS_START';
export const FETCH_TRENDING_TV_SHOWS_SUCCESS =
  'FETCH_TRENDING_TV_SHOWS_SUCCESS';
export const FETCH_TRENDING_TV_SHOWS_FAILED = 'FETCH_TRENDING_TV_SHOWS_FAILED';

export const FETCH_PEOPLE_SEARCH_RESULTS_START =
  'FETCH_PEOPLE_SEARCH_RESULTS_START';
export const FETCH_PEOPLE_SEARCH_RESULTS_SUCCESS =
  'FETCH_PEOPLE_SEARCH_RESULTS_SUCCESS';
export const FETCH_PEOPLE_SEARCH_RESULTS_FAILED =
  'FETCH_PEOPLE_SEARCH_RESULTS_FAILED';

export const FETCH_TRENDING_PEOPLE_START = 'FETCH_TRENDING_PEOPLE_START';
export const FETCH_TRENDING_PEOPLE_SUCCESS = 'FETCH_TRENDING_PEOPLE_SUCCESS';
export const FETCH_TRENDING_PEOPLE_FAILED = 'FETCH_TRENDING_PEOPLE_FAILED';
