export const FETCH_MOVIE_SEARCH_RESULTS_START =
  'FETCH_MOVIE_SEARCH_RESULTS_START';
export const FETCH_MOVIE_SEARCH_RESULTS_SUCCESS =
  'FETCH_MOVIE_SEARCH_RESULTS_SUCCESS';
export const FETCH_MOVIE_SEARCH_RESULTS_FAILED =
  'FETCH_MOVIE_SEARCH_RESULTS_FAILED';

export const FETCH_TV_SHOW_SEARCH_RESULTS_START =
  'FETCH_TV_SHOW_SEARCH_RESULTS_START';
export const FETCH_TV_SHOW_SEARCH_RESULTS_SUCCESS =
  'FETCH_TV_SHOW_SEARCH_RESULTS_SUCCESS';
export const FETCH_TV_SHOW_SEARCH_RESULTS_FAILED =
  'FETCH_TV_SHOW_SEARCH_RESULTS_FAILED';

export const FETCH_PEOPLE_SEARCH_RESULTS_START =
  'FETCH_PEOPLE_SEARCH_RESULTS_START';
export const FETCH_PEOPLE_SEARCH_RESULTS_SUCCESS =
  'FETCH_PEOPLE_SEARCH_RESULTS_SUCCESS';
export const FETCH_PEOPLE_SEARCH_RESULTS_FAILED =
  'FETCH_PEOPLE_SEARCH_RESULTS_FAILED';
