// FETCH MOVIE SEARCHES
export const FETCH_MOVIE_SEARCH_RESULTS_START =
  'FETCH_MOVIE_SEARCH_RESULTS_START';
export const FETCH_MOVIE_SEARCH_RESULTS_SUCCESS =
  'FETCH_MOVIE_SEARCH_RESULTS_SUCCESS';
export const FETCH_MOVIE_SEARCH_RESULTS_FAILED =
  'FETCH_MOVIE_SEARCH_RESULTS_FAILED';

// FETCH TRENDING MOVIES
export const FETCH_TRENDING_MOVIES_START = 'FETCH_TRENDING_MOVIES_START';
export const FETCH_TRENDING_MOVIES_SUCCESS = 'FETCH_TRENDING_MOVIES_SUCCESS';
export const FETCH_TRENDING_MOVIES_FAILED = 'FETCH_TRENDING_MOVIES_FAILED';

// FETCH MOVIE DETAILS
export const FETCH_MOVIE_DETAILS_START = 'FETCH_MOVIE_DETAILS_START';
export const FETCH_MOVIE_DETAILS_SUCCESS = 'FETCH_MOVIE_DETAILS_SUCCESS';
export const FETCH_MOVIE_DETAILS_FAILED = 'FETCH_MOVIE_DETAILS_FAILED';

// FETCH TV SHOW SEARCHES
export const FETCH_TV_SHOW_SEARCH_RESULTS_START =
  'FETCH_TV_SHOW_SEARCH_RESULTS_START';
export const FETCH_TV_SHOW_SEARCH_RESULTS_SUCCESS =
  'FETCH_TV_SHOW_SEARCH_RESULTS_SUCCESS';
export const FETCH_TV_SHOW_SEARCH_RESULTS_FAILED =
  'FETCH_TV_SHOW_SEARCH_RESULTS_FAILED';

// FETCH TRENDING TV SHOWS
export const FETCH_TRENDING_TV_SHOWS_START = 'FETCH_TRENDING_TV_SHOWS_START';
export const FETCH_TRENDING_TV_SHOWS_SUCCESS =
  'FETCH_TRENDING_TV_SHOWS_SUCCESS';
export const FETCH_TRENDING_TV_SHOWS_FAILED = 'FETCH_TRENDING_TV_SHOWS_FAILED';

// FETCH TV SHOW DETAILS
export const FETCH_TV_SHOW_DETAILS_START = 'FETCH_TV_SHOW_DETAILS_START';
export const FETCH_TV_SHOW_DETAILS_SUCCESS = 'FETCH_TV_SHOW_DETAILS_SUCCESS';
export const FETCH_TV_SHOW_DETAILS_FAILED = 'FETCH_TV_SHOW_DETAILS_FAILED';

// FETCH PEOPLE SEARCHES
export const FETCH_PEOPLE_SEARCH_RESULTS_START =
  'FETCH_PEOPLE_SEARCH_RESULTS_START';
export const FETCH_PEOPLE_SEARCH_RESULTS_SUCCESS =
  'FETCH_PEOPLE_SEARCH_RESULTS_SUCCESS';
export const FETCH_PEOPLE_SEARCH_RESULTS_FAILED =
  'FETCH_PEOPLE_SEARCH_RESULTS_FAILED';

// FETCH TRENDING PEOPLE
export const FETCH_TRENDING_PEOPLE_START = 'FETCH_TRENDING_PEOPLE_START';
export const FETCH_TRENDING_PEOPLE_SUCCESS = 'FETCH_TRENDING_PEOPLE_SUCCESS';
export const FETCH_TRENDING_PEOPLE_FAILED = 'FETCH_TRENDING_PEOPLE_FAILED';

// FETCH PERSON DETAILS
export const FETCH_PERSON_DETAILS_START = 'FETCH_PERSON_DETAILS_START';
export const FETCH_PERSON_DETAILS_SUCCESS = 'FETCH_PERSON_DETAILS_SUCCESS';
export const FETCH_PERSON_DETAILS_FAILED = 'FETCH_PERSON_DETAILS_FAILED';

// FETCH CREDITS
export const FETCH_CREDITS_START = 'FETCH_CREDITS_START';
export const FETCH_CREDITS_SUCCESS = 'FETCH_CREDITS_SUCCESS';
export const FETCH_CREDITS_FAILED = 'FETCH_CREDITS_FAILED';

// FETCH TYPEAHEAD RESULTS
export const FETCH_TYPEAHEAD_RESULTS_START = 'FETCH_TYPEAHEAD_RESULTS_START';
export const FETCH_TYPEAHEAD_RESULTS_SUCCESS =
  'FETCH_TYPEAHEAD_RESULTS_SUCCESS';
export const FETCH_TYPEAHEAD_RESULTS_FAILED = 'FETCH_TYPEAHEAD_RESULTS_FAILED';

// MISC TYPEAHEAD ACTIONS
export const CLEAR_TYPEAHEAD = 'CLEAR_TYPEAHEAD';
export const CHANGE_TYPEAHEAD_INPUT = 'CHANGE_TYPEAHEAD_INPUT';
